### ISSUE TITLE
Docker alpine compatibility

### ISSUE THREAD

**Issue by zerjioang** [torusware/speedus-ubuntu#1]
I have seen your .so library works for docker images based on Ubuntu (https://github.com/torusware/speedus-ubuntu/blob/master/xenial/Dockerfile),
but I could not find any information whether it works for alpine. Having it working for alpine would be a great news since it allow to developers to create preety small images.

**Comment by danielfn** [comment]
Hi @zerjioang

I'm afraid that Alpine base images won't be supported for the time being, since it uses a lightweight C library (musl-libc) and currently our builds are targeting glibc. We will let you know if there is any change in the future regarding this support.
